name: rendergan
channels:
- defaults
dependencies:
- python=3.6.6
- pytorch=0.4.1
- scipy
- pip:
  - dominate==2.3.4
  - git+https://github.com/pytorch/vision.git
  - Pillow==5.3.0
  - numpy==1.15.4
  - visdom==0.1.8.5
